### PR TITLE
Addedvercelconfigfiles

### LINKED ISSUE #5: Deployment on Vercel
To enhance the deployment process and improve accessibility, I propose we deploy the project on Vercel. It offers automatic deployments, preview URLs for pull requests, and efficient scaling, which can significantly streamline the workflow.

**Key benefits include:**

- Automatic Deployments: Reduces manual effort and errors.

- Preview Links: Allows for review of changes before merging.

- Scalability: Easily handles increased traffic as we grow.

Implementing this will improve collaboration and make our project more robust.

Kindly assign this issue to me and add the Gssoc, Hacktoberfest, and level2 labels. Thanks

### PR DESCRIPTION
**Pull request by Raj100**
## What does this PR do?
Solve for issue 5 deployment on vercel added vercel config files

Fixes #5 

## Type of change

- New feature (non-breaking change which adds functionality)
## How should this be tested?

- [x] Test A
- [x] Test B

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by iamkanhaiyakumar** [comment]
Hey @Raj100 can you add vercel link

**Comment by Raj100** [comment]
Vercel has to be added by the repository owner other can't add I can give LinkedIn to my fork but it won't update after every change I have added the config files now login to vercel and connect GitHub account and select this repository name it will be added

**Comment by Raj100** [comment]
https://ai-content-generator-grsqcejd6-raj-rawariyas-projects.vercel.app/?vercelToolbarCode=WYAOe0ZzjMlkaEG

**Comment by iamkanhaiyakumar** [comment]
@Raj100 Make ur own vercel site and send because I tried many time but didn't get it so u make ur own personally and me in my LinkedIn

**Pull request merged**
