### PR TITLE
Deploymentonvercel

### LINKED ISSUE #5: Deployment on Vercel
To enhance the deployment process and improve accessibility, I propose we deploy the project on Vercel. It offers automatic deployments, preview URLs for pull requests, and efficient scaling, which can significantly streamline the workflow.

**Key benefits include:**

- Automatic Deployments: Reduces manual effort and errors.

- Preview Links: Allows for review of changes before merging.

- Scalability: Easily handles increased traffic as we grow.

Implementing this will improve collaboration and make our project more robust.

Kindly assign this issue to me and add the Gssoc, Hacktoberfest, and level2 labels. Thanks

### PR DESCRIPTION
**Pull request by Raj100**
## What does this PR do?

Solves issue #5 

Fixes #5 
https://ai-content-generator-yh1f7xdb2-raj-rawariyas-projects.vercel.app/
Screenshot 2024-11-08 at 10 40 41 PM

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [x] Test A
- [x] Test B

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

##Note

Some code were causing errors those had to be commented and the legacy library removed 
on vercel also add the environment variables: (hidden/half for privacy)
Screenshot 2024-11-08 at 10 43 51 PM

### CODE REVIEW

**Comment by GauravKesh** [comment]
@Raj100 preview url is not working

**Comment by Raj100** [comment]
https://ai-content-generator-drab.vercel.app/

**Comment by Raj100** [comment]
Please add the label of ggsoc and hacktoberfest

**Comment by Raj100** [comment]
https://ai-content-generator-drab.vercel.app/

 this link is the same link I give inncorect link before other link is accessible only to me!😅

**Comment by iamkanhaiyakumar** [comment]
You can tell me what is error this cause I didn't deployed in vercel 😴😴

**Comment by Raj100** [comment]
Screenshot 2024-11-10 at 2 40 00 PM
see the changes from file changes majorly the card in dashbboard billing was commented 
and this line in dashboard/layout.tsx was commented
<UpdateCreditUsageContext.Provider value={{ UpdateCreditUsageContext, setUpdateCreditUsage }} > 
rest is fine you can merge it

**Comment by Raj100** [comment]
merge it then uncomment this lines and see the error by doing npm run dev and npm run build

**Comment by GauravKesh** [comment]
@iamkanhaiyakumar We should make it live . Did you try to deploy this ?

**Comment by iamkanhaiyakumar** [comment]
@GauravKesh  I have talked to Raj, he asked me to add some environments, first he asked me to merge this code, so first I will merge it and add that environment, then let's see if it goes live or not. Okay

**Comment by GauravKesh** [comment]
> @GauravKesh I have talked to Raj, he asked me to add some environments, first he asked me to merge this code, so first I will merge it and add that environment, then let's see if it goes live or not. Okay

@iamkanhaiyakumar Yeah sure

**Pull request merged**
