### PR TITLE
Done the enhancements and also added some new sections

### PR DESCRIPTION
**Pull request by milansamuel609**
## What does this PR do?

I have enhanced the document and also added some new sections

Done the following changes :-

1) Enhanced the project structure
2) Added code of conduct section
3) Added star our repository section
4) Added need help with the basics section
5) Added first pull request steps section
6) Added additional method of contributing through GitHub desktop section
7) Added good coding practices section
8) Enhanced the code method, instead of two in single row converted to individual code in the setting up development section which will help to copy each line of code easily.

Fixes:[#36 ]

image

image

image

image

image

image

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by milansamuel609** [comment]
I have done the enhancements. Please kindly check once if all the changes are fine please kindly merge the PR. Also please attach the gssoc extend and level label.

**Review by GauravKesh — CHANGES_REQUESTED** [review]
Need a demo image or video of final readme

**Comment by milansamuel609** [comment]
Screenshot_2024-10-27-01-39-07-31_40deb401b9ffe8e1df2f1cc5ba480b12

Screenshot_2024-10-27-01-39-21-84_40deb401b9ffe8e1df2f1cc5ba480b12

Screenshot_2024-10-27-01-39-33-69_40deb401b9ffe8e1df2f1cc5ba480b12

Screenshot_2024-10-27-01-39-43-76_40deb401b9ffe8e1df2f1cc5ba480b12

These are the images of the final contributing.md file

**Comment by GauravKesh** [comment]
@milansamuel609 Please remove python from the "setting up env section"

**Comment by milansamuel609** [comment]
> @milansamuel609 Please remove python from the "setting up env section"

I have removed it please kindly check it once.

**Pull request merged**
