### PR TITLE
cold mail | resume tailoring tools | cover letter | fixed chatbot related errors

### LINKED ISSUE #40: [Feat]  Cover Letter Generator
### Description

**Description:**  
Implement a feature to generate personalized cover letters for job applications. Users can input job title, company name, and key skills to create a tailored cover letter.

**Requirements:**
- Input fields: job title, company, skills.
- Generate a professional cover letter output.

*Please assign GSSoC-ext and Hacktoberfest labels.*

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### LINKED ISSUE #41: [Feat] Bullet Point Optimizer
**Description:**  
Create a tool that optimizes resume bullet points in an XYZ format (action, task, result).

**Requirements:**
- Input fields: action, task, result.
- Output concise, optimized bullet points.

*Please assign GSSoC-ext and Hacktoberfest labels.*

### LINKED ISSUE #42: [Feat] Resume Optimization Tool
**Description:**  
Add a tool to tailor resumes based on a job description, providing suggestions for keyword alignment.

**Requirements:**
- Input: resume, job description.
- Output: suggested resume improvements.

*Please assign GSSoC-ext and Hacktoberfest labels.*

### LINKED ISSUE #43: [Feat] Cold Mail Generator
### Description

**Description:**  
Develop a tool to generate cold emails for networking or job hunting. Users can specify objectives, such as networking or expressing job interest.

**Requirements:**
- Input: user objective, company, job title.
- Output: professional cold email draft.

*Please assign GSSoC-ext and Hacktoberfest labels.*

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by sezallagwal**
…ated errors

## What does this PR do?

Fixes #42 
Fixes #43  
Fixes #40 
Fixes #41 
Fixed chatbot errors

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by iamkanhaiyakumar** [comment]
Can you the picture and video @sezallagwal

**Comment by sezallagwal** [comment]
image
@iamkanhaiyakumar

**Review by GauravKesh — APPROVED** [review]
we can merge it with main

**Comment by GauravKesh** [comment]
@sezallagwal  Please resolve the conflict in below specified file
`app/(data)/Template.tsx`

**Comment by GauravKesh** [comment]
@sezallagwal great!!

**Pull request merged**
