### PR TITLE
added transitions and effects to the buttons

### PR DESCRIPTION
**Pull request by devxMani**
#17  done you can check

### CODE REVIEW

**Review by GauravKesh — COMMENTED** [review]
@devxMani  All looks good .

can you please attach a image. So we can have a better view of the update in ui.

**Comment by devxMani** [comment]
@GauravKesh bro when i am running the project its showing errors in layout.tsx , and I didn't changed or deleted your logic I only added the tailwind CSS

**Comment by devxMani** [comment]
image

**Comment by GauravKesh** [comment]
@devxMani Okay give me some i'll look into the issue

**Comment by devxMani** [comment]
@GauravKesh okk suree

**Review by GauravKesh — APPROVED** [review]
We can move ahead.

**Pull request merged**
