### PR TITLE
🚀 Automate Connections with GitHub Actions!

### LINKED ISSUE #53: 🚀 Automate Connections with GitHub Actions!
We can implement github workflows for the following things:

Auto comment on issue Closed and Opened
Auto comment on PR mergs
Auto comment on PR raises
Using this workflows makes you'r repo more interactive !

please assign me and i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label
@iamkanhaiyakumar

### PR DESCRIPTION
**Pull request by amiya-cyber**
implemented github workflows for the following things:

Auto comment on issue Closed and Opened
Auto comment on PR mergs
Auto comment on PR raises
Using this workflows makes you'r repo more interactive !

fixes #53 
close #53 

add level2 or level 3 label @iamkanhaiyakumar

### CODE REVIEW

**Comment by iamkanhaiyakumar** [comment]
Add demo pic for final approval @amiya-cyber

**Review by GauravKesh — APPROVED** [review]
@iamkanhaiyakumar I think we can merge it as we don't need any image for this PR

**Comment by amiya-cyber** [comment]
Thank you @GauravKesh and please add level 3 label as gssoc ext is going to over in 2 days and also I have created the entire workflow with 3 new files added

**Comment by amiya-cyber** [comment]
Thanks a lot brother @iamkanhaiyakumar

**Review by MastanSayyad — COMMENTED** [review]
Adding level 2 

image

**Pull request merged**
