### PR TITLE
Updated README File ( Issue #4 )

### PR DESCRIPTION
**Pull request by Ankesh-erek**
The project has been updated ,( Issue- #4 ) with an enhanced README file, providing a clearer structure, detailed installation instructions, and contributing guidelines. It now includes sections like Tech Stack, Features, Installation Guide, and more, to help developers easily understand and contribute to the project.
Please check it once! 
**Thank you for giving this opportunity to contribute.**

### CODE REVIEW

**Comment by iamkanhaiyakumar** [comment]
Tag the issue number

**Comment by Ankesh-erek** [comment]
@iamkanhaiyakumar done sir

**Comment by Ankesh-erek** [comment]
Issue no. - #4

**Comment by Ankesh-erek** [comment]
And I requesting you to please add Hacktoberfest label in this pull request 

> Issue no. - #4

**Pull request merged**
